//! Static arrays of realistic fake data for use in fake data generation mode.

pub const first_names = [_][]const u8{
    "James",       "Mary",      "John",     "Patricia",  "Robert",
    "Jennifer",    "Michael",   "Linda",    "William",   "Barbara",
    "David",       "Elizabeth", "Richard",  "Susan",     "Joseph",
    "Jessica",     "Thomas",    "Sarah",    "Charles",   "Karen",
    "Christopher", "Lisa",      "Daniel",   "Nancy",     "Matthew",
    "Betty",       "Anthony",   "Margaret", "Mark",      "Sandra",
    "Donald",      "Ashley",    "Steven",   "Dorothy",   "Paul",
    "Kimberly",    "Andrew",    "Emily",    "Joshua",    "Donna",
    "Kenneth",     "Michelle",  "Kevin",    "Carol",     "Brian",
    "Amanda",      "George",    "Melissa",  "Timothy",   "Deborah",
    "Ryan",        "Stephanie", "Edward",   "Rebecca",   "Ronald",
    "Sharon",      "Timothy",   "Laura",    "Jason",     "Cynthia",
    "Jeffrey",     "Kathleen",  "Gary",     "Amy",       "Nicholas",
    "Angela",      "Eric",      "Shirley",  "Jonathan",  "Anna",
    "Stephen",     "Brenda",    "Larry",    "Pamela",    "Justin",
    "Emma",        "Scott",     "Nicole",   "Brandon",   "Helen",
    "Benjamin",    "Samantha",  "Samuel",   "Katherine", "Raymond",
    "Christine",   "Gregory",   "Debra",    "Frank",     "Rachel",
    "Alexander",   "Carolyn",   "Patrick",  "Janet",     "Jack",
    "Catherine",   "Dennis",    "Maria",    "Jerry",     "Heather",
};

pub const last_names = [_][]const u8{
    "Smith",     "Johnson",  "Williams", "Brown",      "Jones",
    "Garcia",    "Miller",   "Davis",    "Rodriguez",  "Martinez",
    "Hernandez", "Lopez",    "Gonzalez", "Wilson",     "Anderson",
    "Thomas",    "Taylor",   "Moore",    "Jackson",    "Martin",
    "Lee",       "Perez",    "Thompson", "White",      "Harris",
    "Sanchez",   "Clark",    "Ramirez",  "Lewis",      "Robinson",
    "Walker",    "Young",    "Allen",    "King",       "Wright",
    "Scott",     "Torres",   "Nguyen",   "Hill",       "Flores",
    "Green",     "Adams",    "Nelson",   "Baker",      "Hall",
    "Rivera",    "Campbell", "Mitchell", "Carter",     "Roberts",
    "Phillips",  "Evans",    "Turner",   "Parker",     "Collins",
    "Edwards",   "Stewart",  "Morris",   "Murphy",     "Cook",
    "Rogers",    "Morgan",   "Peterson", "Cooper",     "Reed",
    "Bailey",    "Bell",     "Gomez",    "Kelly",      "Howard",
    "Ward",      "Cox",      "Diaz",     "Richardson", "Wood",
    "Watson",    "Brooks",   "Bennett",  "Gray",       "James",
    "Reyes",     "Cruz",     "Hughes",   "Price",      "Myers",
    "Long",      "Foster",   "Sanders",  "Ross",       "Morales",
    "Powell",    "Sullivan", "Russell",  "Ortiz",      "Jenkins",
    "Gutierrez", "Perry",    "Butler",   "Barnes",     "Fisher",
};

pub const job_titles = [_][]const u8{
    "Software Engineer",            "Product Manager",
    "Data Scientist",               "UX Designer",
    "DevOps Engineer",              "Systems Architect",
    "Marketing Manager",            "Sales Representative",
    "Financial Analyst",            "Human Resources Manager",
    "Operations Manager",           "Project Manager",
    "Business Analyst",             "Quality Assurance Engineer",
    "Database Administrator",       "Network Engineer",
    "Security Analyst",             "Cloud Architect",
    "Machine Learning Engineer",    "Backend Developer",
    "Frontend Developer",           "Full Stack Developer",
    "Mobile Developer",             "Technical Writer",
    "Customer Success Manager",     "Scrum Master",
    "Chief Technology Officer",     "Chief Executive Officer",
    "Chief Operating Officer",      "Vice President of Engineering",
    "Site Reliability Engineer",    "Platform Engineer",
    "Data Engineer",                "Data Analyst",
    "Solutions Architect",          "Enterprise Architect",
    "IT Manager",                   "IT Director",
    "Software Architect",           "Engineering Manager",
    "Product Designer",             "UX Researcher",
    "Growth Hacker",                "Digital Marketing Specialist",
    "Content Strategist",           "Brand Manager",
    "Account Executive",            "Account Manager",
    "Business Development Manager", "Chief Marketing Officer",
    "Chief Financial Officer",      "General Counsel",
    "Legal Counsel",                "Compliance Officer",
    "Risk Manager",                 "Procurement Manager",
    "Supply Chain Manager",         "Logistics Coordinator",
    "Customer Support Specialist",  "Technical Support Engineer",
    "Research Scientist",           "Biomedical Engineer",
};

pub const cities = [_][]const u8{
    // United States
    "New York",       "Los Angeles",      "Chicago",          "Houston",
    "Phoenix",        "Philadelphia",     "San Antonio",      "San Diego",
    "Dallas",         "San Jose",         "Austin",           "Jacksonville",
    "Fort Worth",     "Columbus",         "Charlotte",        "Indianapolis",
    "San Francisco",  "Seattle",          "Denver",           "Nashville",
    "Oklahoma City",  "El Paso",          "Washington",       "Las Vegas",
    "Louisville",     "Memphis",          "Portland",         "Baltimore",
    "Milwaukee",      "Albuquerque",      "Tucson",           "Fresno",
    "Sacramento",     "Kansas City",      "Mesa",             "Atlanta",
    "Omaha",          "Colorado Springs", "Raleigh",          "Long Beach",
    "Virginia Beach", "Minneapolis",      "Tampa",            "New Orleans",
    "Arlington",      "Wichita",          "Cleveland",        "Bakersfield",
    "Aurora",         "Anaheim",          "Miami",            "Boston",
    "Detroit",        "Pittsburgh",       "St. Louis",        "Cincinnati",
    "Orlando",        "Salt Lake City",   "Buffalo",          "Newark",
    // World capitals
    "Kabul",          "Tirana",           "Algiers",          "Andorra la Vella",
    "Luanda",         "Buenos Aires",     "Yerevan",          "Canberra",
    "Vienna",         "Baku",             "Nassau",           "Manama",
    "Dhaka",          "Bridgetown",       "Minsk",            "Brussels",
    "Belmopan",       "Porto-Novo",       "Thimphu",          "Sucre",
    "Sarajevo",       "Gaborone",         "Brasilia",         "Sofia",
    "Ouagadougou",    "Gitega",           "Praia",            "Phnom Penh",
    "Yaounde",        "Ottawa",           "Bangui",           "Santiago",
    "Beijing",        "Bogota",           "Moroni",           "Brazzaville",
    "San Jose",       "Yamoussoukro",     "Zagreb",           "Havana",
    "Nicosia",        "Prague",           "Kinshasa",         "Copenhagen",
    "Djibouti",       "Roseau",           "Santo Domingo",    "Quito",
    "Cairo",          "San Salvador",     "Malabo",           "Asmara",
    "Tallinn",        "Mbabane",          "Addis Ababa",      "Suva",
    "Helsinki",       "Paris",            "Libreville",       "Banjul",
    "Tbilisi",        "Berlin",           "Accra",            "Athens",
    "Guatemala City", "Conakry",          "Bissau",           "Georgetown",
    "Tegucigalpa",    "Budapest",         "Reykjavik",        "New Delhi",
    "Jakarta",        "Tehran",           "Baghdad",          "Dublin",
    "Jerusalem",      "Rome",             "Kingston",         "Tokyo",
    "Amman",          "Astana",           "Nairobi",          "Tarawa",
    "Kuwait City",    "Bishkek",          "Vientiane",        "Riga",
    "Beirut",         "Maseru",           "Monrovia",         "Tripoli",
    "Vaduz",          "Vilnius",          "Luxembourg City",  "Antananarivo",
    "Lilongwe",       "Kuala Lumpur",     "Male",             "Bamako",
    "Valletta",       "Majuro",           "Nouakchott",       "Port Louis",
    "Mexico City",    "Palikir",          "Chisinau",         "Monaco",
    "Ulaanbaatar",    "Podgorica",        "Rabat",            "Maputo",
    "Naypyidaw",      "Windhoek",         "Kathmandu",        "Amsterdam",
    "Wellington",     "Managua",          "Niamey",           "Abuja",
    "Pyongyang",      "Skopje",           "Oslo",             "Muscat",
    "Islamabad",      "Ngerulmud",        "Ramallah",         "Panama City",
    "Port Moresby",   "Asuncion",         "Lima",             "Manila",
    "Warsaw",         "Lisbon",           "Doha",             "Bucharest",
    "Moscow",         "Kigali",           "Basseterre",       "Castries",
    "Kingstown",      "Apia",             "San Marino",       "Riyadh",
    "Dakar",          "Belgrade",         "Victoria",         "Freetown",
    "Singapore",      "Bratislava",       "Ljubljana",        "Honiara",
    "Mogadishu",      "Pretoria",         "Seoul",            "Juba",
    "Madrid",         "Colombo",          "Khartoum",         "Paramaribo",
    "Stockholm",      "Bern",             "Damascus",         "Dushanbe",
    "Dodoma",         "Bangkok",          "Dili",             "Lome",
    "Nukualofa",      "Port of Spain",    "Tunis",            "Ankara",
    "Ashgabat",       "Funafuti",         "Kampala",          "Kyiv",
    "Abu Dhabi",      "London",           "Montevideo",       "Tashkent",
    "Port Vila",      "Vatican City",     "Caracas",          "Hanoi",
    "Sanaa",          "Lusaka",           "Harare",
    // Major non-capital world cities
              "Sydney",
    "Melbourne",      "Brisbane",         "Perth",            "Toronto",
    "Montreal",       "Vancouver",        "Calgary",          "Shanghai",
    "Shenzhen",       "Guangzhou",        "Chengdu",          "Hong Kong",
    "Mumbai",         "Delhi",            "Bangalore",        "Chennai",
    "Kolkata",        "Hyderabad",        "Pune",             "Sao Paulo",
    "Rio de Janeiro", "Salvador",         "Fortaleza",        "Guadalajara",
    "Monterrey",      "Puebla",           "Tijuana",          "Osaka",
    "Yokohama",       "Nagoya",           "Sapporo",          "Busan",
    "Incheon",        "Daegu",            "Daejeon",          "Istanbul",
    "Izmir",          "Bursa",            "Antalya",          "Lagos",
    "Kano",           "Ibadan",           "Kaduna",           "Cape Town",
    "Johannesburg",   "Durban",           "Soweto",           "Casablanca",
    "Marrakech",      "Fes",              "Tangier",          "Alexandria",
    "Giza",           "Luxor",            "Aswan",            "Naples",
    "Milan",          "Turin",            "Palermo",          "Barcelona",
    "Valencia",       "Seville",          "Bilbao",           "Hamburg",
    "Munich",         "Frankfurt",        "Cologne",          "Lyon",
    "Marseille",      "Toulouse",         "Nice",             "Rotterdam",
    "The Hague",      "Utrecht",          "Eindhoven",        "Gothenburg",
    "Malmo",          "Uppsala",          "Dubai",            "Sharjah",
    "Ajman",          "Karachi",          "Lahore",           "Faisalabad",
    "Rawalpindi",     "Chittagong",       "Khulna",           "Rajshahi",
    "Yangon",         "Mandalay",         "Ho Chi Minh City", "Da Nang",
    "Hai Phong",      "Chiang Mai",       "Phuket",           "Medina",
    "Jeddah",         "Mecca",            "Kumasi",           "Tamale",
    "Mombasa",        "Kisumu",           "Entebbe",          "Gulu",
    "Dire Dawa",      "Gondar",           "Auckland",         "Christchurch",
    "Hamilton",       "Edinburgh",        "Glasgow",          "Manchester",
    "Birmingham",     "Leeds",            "Bristol",          "Zurich",
    "Geneva",         "Basel",            "Lausanne",         "Krakow",
    "Wroclaw",        "Poznan",           "Brno",             "Ostrava",
    "Debrecen",       "Pecs",             "Cluj-Napoca",      "Timisoara",
    "Kharkiv",        "Odessa",           "Lviv",             "Gomel",
    "Brest",          "Almaty",           "Shymkent",         "Karaganda",
    "Samarkand",      "Namangan",         "Ganja",            "Sumqayit",
    "Kutaisi",        "Batumi",           "Gyumri",           "Vanadzor",
};

pub const countries = [_][]const u8{
    "Afghanistan",                      "Albania",            "Algeria",
    "Andorra",                          "Angola",             "Antigua and Barbuda",
    "Argentina",                        "Armenia",            "Australia",
    "Austria",                          "Azerbaijan",         "Bahamas",
    "Bahrain",                          "Bangladesh",         "Barbados",
    "Belarus",                          "Belgium",            "Belize",
    "Benin",                            "Bhutan",             "Bolivia",
    "Bosnia and Herzegovina",           "Botswana",           "Brazil",
    "Brunei",                           "Bulgaria",           "Burkina Faso",
    "Burundi",                          "Cabo Verde",         "Cambodia",
    "Cameroon",                         "Canada",             "Central African Republic",
    "Chad",                             "Chile",              "China",
    "Colombia",                         "Comoros",            "Congo",
    "Costa Rica",                       "Ivory Coast",        "Croatia",
    "Cuba",                             "Cyprus",             "Czech Republic",
    "Democratic Republic of the Congo", "Denmark",            "Djibouti",
    "Dominica",                         "Dominican Republic", "Ecuador",
    "Egypt",                            "El Salvador",        "Equatorial Guinea",
    "Eritrea",                          "Estonia",            "Eswatini",
    "Ethiopia",                         "Fiji",               "Finland",
    "France",                           "Gabon",              "Gambia",
    "Georgia",                          "Germany",            "Ghana",
    "Greece",                           "Grenada",            "Guatemala",
    "Guinea",                           "Guinea-Bissau",      "Guyana",
    "Haiti",                            "Honduras",           "Hungary",
    "Iceland",                          "India",              "Indonesia",
    "Iran",                             "Iraq",               "Ireland",
    "Israel",                           "Italy",              "Jamaica",
    "Japan",                            "Jordan",             "Kazakhstan",
    "Kenya",                            "Kiribati",           "Kuwait",
    "Kyrgyzstan",                       "Laos",               "Latvia",
    "Lebanon",                          "Lesotho",            "Liberia",
    "Libya",                            "Liechtenstein",      "Lithuania",
    "Luxembourg",                       "Madagascar",         "Malawi",
    "Malaysia",                         "Maldives",           "Mali",
    "Malta",                            "Marshall Islands",   "Mauritania",
    "Mauritius",                        "Mexico",             "Micronesia",
    "Moldova",                          "Monaco",             "Mongolia",
    "Montenegro",                       "Morocco",            "Mozambique",
    "Myanmar",                          "Namibia",            "Nauru",
    "Nepal",                            "Netherlands",        "New Zealand",
    "Nicaragua",                        "Niger",              "Nigeria",
    "North Korea",                      "North Macedonia",    "Norway",
    "Oman",                             "Pakistan",           "Palau",
    "Palestine",                        "Panama",             "Papua New Guinea",
    "Paraguay",                         "Peru",               "Philippines",
    "Poland",                           "Portugal",           "Qatar",
    "Romania",                          "Russia",             "Rwanda",
    "Saint Kitts and Nevis",            "Saint Lucia",        "Saint Vincent and the Grenadines",
    "Samoa",                            "San Marino",         "Sao Tome and Principe",
    "Saudi Arabia",                     "Senegal",            "Serbia",
    "Seychelles",                       "Sierra Leone",       "Singapore",
    "Slovakia",                         "Slovenia",           "Solomon Islands",
    "Somalia",                          "South Africa",       "South Korea",
    "South Sudan",                      "Spain",              "Sri Lanka",
    "Sudan",                            "Suriname",           "Sweden",
    "Switzerland",                      "Syria",              "Tajikistan",
    "Tanzania",                         "Thailand",           "Timor-Leste",
    "Togo",                             "Tonga",              "Trinidad and Tobago",
    "Tunisia",                          "Turkey",             "Turkmenistan",
    "Tuvalu",                           "Uganda",             "Ukraine",
    "United Arab Emirates",             "United Kingdom",     "United States",
    "Uruguay",                          "Uzbekistan",         "Vanuatu",
    "Vatican City",                     "Venezuela",          "Vietnam",
    "Yemen",                            "Zambia",             "Zimbabwe",
};

pub const streets = [_][]const u8{
    "Main Street",        "Oak Avenue",      "Maple Drive",     "Cedar Lane",
    "Elm Street",         "Park Boulevard",  "Washington Road", "Jefferson Way",
    "Lincoln Avenue",     "Madison Street",  "Monroe Drive",    "Adams Lane",
    "Franklin Boulevard", "Harrison Street", "Tyler Road",      "Polk Avenue",
    "Taylor Drive",       "Fillmore Lane",   "Pierce Street",   "Buchanan Way",
    "Highland Avenue",    "River Road",      "Lake Street",     "Forest Drive",
    "Sunset Boulevard",   "Sunrise Lane",    "Valley Road",     "Mountain View",
    "Ocean Avenue",       "Beach Boulevard",
};

pub const email_domains = [_][]const u8{
    "gmail.com",    "yahoo.com",      "hotmail.com", "outlook.com",
    "icloud.com",   "protonmail.com", "mail.com",    "zoho.com",
    "fastmail.com", "tutanota.com",
};

pub const company_domains = [_][]const u8{
    "acme.com",     "globex.com",    "umbrella.com", "initech.com",
    "hooli.com",    "piedpiper.com", "dunder.com",   "waystar.com",
    "veridian.com", "cyberdyne.com", "aperture.com", "weyland.com",
    "nakatomi.com", "abstergo.com",  "oscorp.com",   "stark.com",
};

pub const company_names = [_][]const u8{
    "Acme Corporation",    "Global Industries",  "Tech Solutions Inc.",
    "Digital Dynamics",    "Future Systems",     "Innovation Labs",
    "Strategic Partners",  "Premier Services",   "Elite Technologies",
    "Advanced Solutions",  "Prime Consulting",   "Next Generation Tech",
    "Alpha Enterprises",   "Beta Technologies",  "Gamma Systems",
    "Delta Solutions",     "Omega Corp",         "Apex Industries",
    "Summit Technologies", "Pinnacle Solutions",
};

pub const tlds = [_][]const u8{
    "com", "net", "org", "io", "co", "dev", "app", "tech", "info", "biz",
};

pub const hostnames_prefix = [_][]const u8{
    "api", "web", "app", "mail", "ftp", "smtp", "pop3",  "imap",
    "db",  "srv", "cdn", "ns1",  "ns2", "vpn",  "proxy", "lb",
};

pub const currency_names = [_][]const u8{
    "United States Dollar", "Euro",             "British Pound Sterling",
    "Japanese Yen",         "Canadian Dollar",  "Swiss Franc",
    "Australian Dollar",    "Chinese Yuan",     "Hong Kong Dollar",
    "Swedish Krona",        "Norwegian Krone",  "Danish Krone",
    "New Zealand Dollar",   "Singapore Dollar", "South Korean Won",
    "Indian Rupee",         "Brazilian Real",   "Mexican Peso",
    "South African Rand",   "Turkish Lira",
};

pub const currency_codes = [_][]const u8{
    "USD", "EUR", "GBP", "JPY", "CAD", "CHF", "AUD", "CNY", "HKD", "SEK",
    "NOK", "DKK", "NZD", "SGD", "KRW", "INR", "BRL", "MXN", "ZAR", "TRY",
};

pub const lorem_words = [_][]const u8{
    "lorem",        "ipsum",      "dolor",      "sit",           "amet",
    "consectetur",  "adipiscing", "elit",       "sed",           "do",
    "eiusmod",      "tempor",     "incididunt", "ut",            "labore",
    "et",           "dolore",     "magna",      "aliqua",        "enim",
    "ad",           "minim",      "veniam",     "quis",          "nostrud",
    "exercitation", "ullamco",    "laboris",    "nisi",          "aliquip",
    "ex",           "ea",         "commodo",    "consequat",     "duis",
    "aute",         "irure",      "in",         "reprehenderit", "voluptate",
    "velit",        "esse",       "cillum",     "eu",            "fugiat",
    "nulla",        "pariatur",   "excepteur",  "sint",          "occaecat",
};
